//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMusteri
    {
        public int musteriID { get; set; }
        public string musteriFirma { get; set; }
        public string musteriSifre { get; set; }
        public string musteriMail { get; set; }
        public string musteriTel { get; set; }
        public string musteriAddress { get; set; }
        public string ekstrayap { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string yapilacak { get; set; }
    }
}
