//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMesajlar
    {
        public int MesajID { get; set; }
        public int GonderenID { get; set; }
        public int AliciID { get; set; }
        public string Icerik { get; set; }
    }
}
