//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersonel
    {
        public int personelID { get; set; }
        public string PersonelAd { get; set; }
        public string personelSoyad { get; set; }
        public string personelUnvan { get; set; }
        public string personelKullanici { get; set; }
        public string personelSifre { get; set; }
        public string PersonelNot { get; set; }
    }
}
